# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quote', models.CharField(max_length=500)),
                ('source', models.CharField(max_length=50)),
            ],
            options={
                'managed': False,
                'db_table': 'quotes',
            },
        ),
    ]
